### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by jema28** [fack2/translationApplication#18]
As you only have a few files in this project it's best practice to include all files/folders in the `public` folder, like this:

public
-- index.html
-- style.css
-- script.js

**Comment by jema28** [comment]
Note: file names are usually lowercase e.g. `dom.js` vs `Dom.js` 💄

**Comment by Muniralsharif** [comment]
we reorganise  the files == fixed  @jema28

**Comment by Muniralsharif** [comment]
chinging Dom.js to dom.js is done @jema28
