### ISSUE TITLE
Accessibility is only 58! 

### ISSUE THREAD

**Issue by sara219** [fack2/translationApplication#20]

**Comment by jema28** [comment]
@sara219 it would be great to add a screenshot here like this: 

<img width="668" alt="Screenshot 2019-07-04 at 09 04 26" src="https://user-images.githubusercontent.com/25960351/60643142-d7f59b00-9e3a-11e9-9161-315927a6108b.png">

**Comment by Muniralsharif** [comment]
fixed now is 100% @sara219 @jema28
