### ISSUE TITLE
typeError: 'selectedIndex' is null

### ISSUE THREAD

**Issue by jema28** [fack2/translationApplication#22]
This line currently isn't working `var selectedLang = inputLang[inputLang.selectedIndex].value;` and therefore translateUrl doesn't work.

<img width="1301" alt="Screenshot 2019-07-04 at 08 52 12" src="https://user-images.githubusercontent.com/25960351/60642577-0f634800-9e39-11e9-9d90-db4625c88ed2.png">

**Comment by Muniralsharif** [comment]
fixed @jema28
