### ISSUE TITLE
App style on mobiles

### ISSUE THREAD

**Issue by ameentalahmeh** [fack2/translationApplication#24]
You have great work through the idea and design, but your app needs to more styling particularly on **mobiles** platforms related to: 
1. Font size
2. Big white spaces (not necessary) 

See the picture:
![Screenshot from 2019-07-04 09-08-54](https://user-images.githubusercontent.com/26909309/60643565-1b9cd480-9e3c-11e9-95f7-35baf66c2fc4.png)

**Comment by Muniralsharif** [comment]
fixed @ameentalahmeh
