### ISSUE TITLE
pure functions

### ISSUE THREAD

**Issue by Hadeel-Salamin** [fack2/translationApplication#25]
I would prefer to write a method passing the language shortcut as a parameter and return the language name and call it inside the request method instead of having this switch cases here 

https://github.com/fack2/translationApplication/blob/9cad1189492f46120da34836d0c3260a2851a0f6/frontend/Dom.js#L26

It would be more clear, also by doing this, you could have a pure function to test as you already have a file for tests but has nothing being tested.

**Comment by Muniralsharif** [comment]
fixed @Hadeel-Salamin
