### ISSUE TITLE
Commit messages

### ISSUE THREAD

**Issue by jema28** [fack2/translationApplication#27]
What did you work in these commits? It's best to avoid saying 'nearly finished' or 'last version' (as you'll probably work on the CSS again) so the commit history can help you look back/tell a story of what you worked on. Does this make sense @RandInaim @Muniralsharif?

<img width="765" alt="Screenshot 2019-07-04 at 09 22 03" src="https://user-images.githubusercontent.com/25960351/60643902-3754aa80-9e3d-11e9-9feb-d15140cdc8b4.png">

**Comment by Muniralsharif** [comment]
Thanks, @jema28 I got it and ill work on it in future
